[imdb]
BaseURL             = "https://datasets.imdbws.com/"
Files = ["name.basics", "title.akas", "title.basics", "title.crew", "title.episode", "title.principals", "title.ratings"]

#[database]
#server = "34.89.112.196"
#port = 5432
#user = "sqlbot"
#password = "SXDvkORMmRRfNP6s0CEADIh60"
#dbname = "sqlbot"
#sslmode = "disable"

[database]
server = "0.0.0.0"
port = 5432
user = "superset"
password = "superset"
dbname = "imdb"
sslmode = "disable"
[server]
bind = "0.0.0.0"
port = 3000

[fs]
tempdir = ""